### ISSUE TITLE
Is it okay to begin using this API?

### ISSUE THREAD

**Issue by mike-sfg** [getbible/v2#1]
@Llewellynvdm Thank you for all of your hard work on this!

Is it okay to begin making use of v2 of the API in our websites/applications?

Also, I understand you plan to update/rewrite the Joomla-3-GetBible component at a future date.

**Comment by Llewellynvdm** [comment]
> Is it okay to begin making use of v2 of the API in our websites/applications?
Yes!

> ...update/rewrite the Joomla-3-GetBible component at a future date.
Yes based on version 2
