### ISSUE TITLE
How can I programmatically stay in sync with getbible v2?

### ISSUE THREAD

**Issue by lancejpollard** [getbible/v2#12]
What do I need to do at a medium-to-high level of detail, to keep my JSON records in sync with getbible v2 (which in turn is in sync with Crosswire, which I am curious about in my other issue I opened up :))?

- Do I need to run some sort of cron job, or get notified of changes by webhooks, sort of thing?
- How do I bootstrap the initial "clone" of data so to speak?
- What else do I need to know to keep things updated and in sync after the initial bootstrapping?

Thank you so much for all the effort you put into this! It seems like a really well done project so far that I can see.

**Comment by Llewellynvdm** [comment]
What I did to help with this is add a `hash` as you probably already know to each chapter, book, version. So initially all you need to do is cache these hash values. Then to monitor only the version, if one of them change, then you can check the hash of which book changed, and then which chapter and only update those. Well that is the idea.

How to pull or as you call it clone is via the API, as demonstrated in the [README](https://github.com/getbible/v2#how-will-this-work) documentation. There is a endpoint for each chapter, book, and version. We also tried to keep the verse level format the same across each level of the API.

So looking at our example:
https://getbible.net/v2/kjv/62/3.json  (chapter)
https://getbible.net/v2/kjv/62.json  (book)
https://getbible.net/v2/kjv.json  (version)

The hash values for these are found as follow:
https://getbible.net/v2/checksum.json (all versions)
https://getbible.net/v2/kjv/checksum.json (books of a version)
https://getbible.net/v2/kjv/62/checksum.json (chapters of a book)

SO how you keep your self connected to these changing values is up to you. But it should be simple enough that your script does a check one a week, or once a month to see if anything changed. Then to follow whatever process you think best suites your needs to updated accordingly. Note that our systems run [only once a month](https://github.com/getbible/v2_builder/blob/staging/.github/workflows/build.yml#L4).

So the repository where the actual scripture is hosted is private, and the only way to get the scripture is via the API. Storing it is discouraged, but if its stored the HASH updating method must be implemented to bet true to our commitments, and respect the wishes of those we depend on downstream.

> Would be amazing if someone would write a fully integrated JavaScript library on-top of this API, and that we can add it to this repository for others to use.

**Comment by Llewellynvdm** [comment]
### Centralizing Support to a Single Location

We're excited to share that we've streamlined our support process for all GetBible projects to a single repository for greater efficiency and quicker response times. You can access this at: https://git.vdm.dev/getBible/support

Consequently, we'll be closing this issue here. Should you wish to respond, or if you encounter any new issues, kindly utilize the new Support Repository. We're confident this will help us respond to your concerns in a more timely manner.

Thank you for your understanding and continued support!
