### ISSUE TITLE
How to get only one verse or a range of verses

### ISSUE THREAD

**Issue by gildasawesso** [getbible/v2#15]
Hello, and good job for this project.

I'm migrating from old api to v2 api but I'm missing the documentation on how to just retrieve only the verse or a range of verse. Actually I'm getting the whole chapter, this is not what I want. How to get one verse or a range of verse with this v2 api ?

Thank you

**Comment by Llewellynvdm** [comment]
Greetings @gildasawesso there will be a new API endpoint on the new system for verse ranges.

For now I have moved the old system to `https://archived.getbible.net/` and it should work as before, this should give you time to move over to the new system while your application can still use the old access points.

So you should be able to use:
```
https://archived.getbible.net/json?passage=1Jn3:16
```

> So from the moment the new system is up and running and we have the new API documented, we will keep the ARCHIVED system for 6 months, and then we will completely remove it. This means you will have six months from the moment we have the new API up and running to move over to the new API.

We hope to release the **new verse range API** **July 31th**
