### ISSUE TITLE
Wordpress Plugin

### ISSUE THREAD

**Issue by rags2gars** [getbible/v2#4]
I have a Wordpress site that had a plugin to embed chapters of Psalms in Hebrew on various pages of my site. All those plugins are no longer supported and I've been searching for an alternative. Would this API work instead? If so, how would I accomplish that? Sorry for the newbie question.

**Comment by Llewellynvdm** [comment]
Yes it could work, but you would need to write your own JavaScript to achieve this.

**Comment by rags2gars** [comment]
Thanks for the prompt reply. I guess I'm off to find someone who can write Javascript.

**Comment by rags2gars** [comment]
I see that in V1 you had the OT WLC version but I'm not seeing that in the V2. Only the Aleppo which has no vowels. Am I missing something?

**Comment by JoshuaCrewe** [comment]
@rags2gars  what sort of functionality are you looking for? Is there a particular plugin that you were using you can link to which shows what you need?

**Comment by JoshuaCrewe** [comment]
@rags2gars did you get it sorted ?
