### ISSUE TITLE
Can this API be used in Android applications

### ISSUE THREAD

**Issue by lenvaz** [getbible/v2#7]
I am planning to make an android application and hopefully deploy it to play store. So i was thinking if this API can be used for that purpose.

As currently I tried integrating it and i get the CORS issue as bellow.

:51210/#/:1 Access to XMLHttpRequest at 'https://getbible.net/v2/kjv/books.json' from origin 'http://localhost:51210' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Please let me know if this is possible.

**Comment by Llewellynvdm** [comment]
Please take a look at this [app](https://github.com/getbible/app) that another team of developers started, see if you can join their contribution. I know they are trying to make the app work offline, and to add search... and more.

I have not yet had time to look at the work in detail. But will eventually like to list this as well once I have had time to evaluate all the code. They already use the API, so even if you choose not to contribute, you can still see how they interact with the API.
